exclude_paths:
  - "frontend/javascript/modules/vue.js"
  - "frontend/media/**/*.*"
  - "**/*.html"
  - "phpunit.phar"
languages:
  PHP: true
  javascript: true
ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.pug"
  - "**/styles"
