sudo: required
dist: trusty
notifications:
  email: false
language: php
php:
  - 7.0
language: node_js
node_js:
  - 8.0.0
services: mongodb
env:
  - NODE_PATH=.
  - NODE_ENV=test
script:
  - npm run coveragenyc
script:
  php phpunit.phar
