# coffee file
default:
  description: 'Build porject' 
  tasks:
    - 'clean'
    - 'pug'
    - 'html-prettyprinter-dir'
    - 'processhtml:production'
    - 'wiredep:production'
    - 'imagemin'
    - 'sprite'
    - 'svg_sprite'
    - 'cssjoin'
    - 'copyto:stuff'
    - 'copy'
    - 'browserify'
    - 'concat:dist'
    - 'uglify:build'
    - 'less_imports'
    - 'less'
    - 'sass_include'
    - 'sass'
    - 'stylus'
    - 'autoprefixer'
    - 'cssmin:banner'
    - 'string-replace'
    - 'concat:libsJs'
    - 'uglify:libs'
    - 'concat:allJs'
    - 'cssmin:libs'
    - 'concat:libsCss'
dev:
  tasks:
    - 'clean'
    - 'pug'
    - 'html-prettyprinter-dir'
    - 'wiredep:development'
    - 'processhtml:development'
    - 'imagemin'
    - 'sprite'
    - 'svg_sprite'
    - 'cssjoin'
    - 'copyto:stuff'
    - 'copy'
    - 'browserify'
    - 'concat:dist'
    - 'less_imports'
    - 'less'
    - 'sass_include'
    - 'sass'
    - 'stylus'
    - 'php'
    - 'browserSync'
    - 'watch'
